2019-03-08 10:53:25 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Table "PLAY_EVOLUTIONS" not found; SQL statement:
select id, hash, apply_script, revert_script, state, last_problem from play_evolutions where state like 'applying_%' [42102-197]
2019-03-13 10:52:10 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Column "JOBTITLE" not found; SQL statement:
insert into employee (email, role, jobTitle, workPhone, salary, password)
            values ('employee@jmc.com', 'employee','secretary','08512345678',25000.00, 'password') [42122-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.table.Table.getColumn(Table.java:682)
	at org.h2.command.Parser.parseColumn(Parser.java:936)
	at org.h2.command.Parser.parseColumnList(Parser.java:920)
	at org.h2.command.Parser.parseInsertGivenTable(Parser.java:1258)
	at org.h2.command.Parser.parseInsert(Parser.java:1222)
	at org.h2.command.Parser.parsePrepared(Parser.java:431)
	at org.h2.command.Parser.parse(Parser.java:335)
	at org.h2.command.Parser.parse(Parser.java:307)
	at org.h2.command.Parser.prepareCommand(Parser.java:278)
	at org.h2.engine.Session.prepareLocal(Session.java:611)
	at org.h2.engine.Session.prepareCommand(Session.java:549)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1247)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:217)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:1077)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1386)
	at org.h2.server.web.WebApp.query(WebApp.java:1060)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1022)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1009)
	at org.h2.server.web.WebThread.process(WebThread.java:165)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.lang.Thread.run(Thread.java:748)
2019-03-15 22:56:40 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Column count does not match; SQL statement:
insert into employee (email, role, name, job_Title, work_Phone, salary, password,department_id)
            values ('BillMorris@jmc.com','employee','Bill Morris','Auditor','08512345678',35000.00, 'password',3,1) [21002-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.command.dml.Insert.prepare(Insert.java:306)
	at org.h2.command.Parser.prepareCommand(Parser.java:283)
	at org.h2.engine.Session.prepareLocal(Session.java:611)
	at org.h2.engine.Session.prepareCommand(Session.java:549)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1247)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:217)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:1077)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1386)
	at org.h2.server.web.WebApp.query(WebApp.java:1060)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1022)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1009)
	at org.h2.server.web.WebThread.process(WebThread.java:165)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.lang.Thread.run(Thread.java:748)
2019-03-15 22:56:40 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Column count does not match; SQL statement:
insert into employee (email, role, name, job_Title, work_Phone, salary, password,department_id)
            values ('HenriettaFord@jmc.com','manager','HenriettaFord','manager','08512345678',40000.00, 'password',4,1) [21002-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.command.dml.Insert.prepare(Insert.java:306)
	at org.h2.command.Parser.prepareCommand(Parser.java:283)
	at org.h2.engine.Session.prepareLocal(Session.java:611)
	at org.h2.engine.Session.prepareCommand(Session.java:549)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1247)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:217)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:1077)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1386)
	at org.h2.server.web.WebApp.query(WebApp.java:1060)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1022)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1009)
	at org.h2.server.web.WebThread.process(WebThread.java:165)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.lang.Thread.run(Thread.java:748)
2019-03-15 22:58:05 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Column count does not match; SQL statement:
insert into employee (email, role, name, job_Title, work_Phone, salary, password,department_id)
            values ('BillMorris@jmc.com','employee','Bill Morris','Auditor','08512345678',35000.00, 'password',3,1) [21002-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.command.dml.Insert.prepare(Insert.java:306)
	at org.h2.command.Parser.prepareCommand(Parser.java:283)
	at org.h2.engine.Session.prepareLocal(Session.java:611)
	at org.h2.engine.Session.prepareCommand(Session.java:549)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1247)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:217)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:1077)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1386)
	at org.h2.server.web.WebApp.query(WebApp.java:1060)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1022)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1009)
	at org.h2.server.web.WebThread.process(WebThread.java:165)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.lang.Thread.run(Thread.java:748)
2019-03-15 22:58:05 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Column count does not match; SQL statement:
insert into employee (email, role, name, job_Title, work_Phone, salary, password,department_id)
            values ('HenriettaFord@jmc.com','manager','HenriettaFord','manager','08512345678',40000.00, 'password',4,1) [21002-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.command.dml.Insert.prepare(Insert.java:306)
	at org.h2.command.Parser.prepareCommand(Parser.java:283)
	at org.h2.engine.Session.prepareLocal(Session.java:611)
	at org.h2.engine.Session.prepareCommand(Session.java:549)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1247)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:217)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:1077)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1386)
	at org.h2.server.web.WebApp.query(WebApp.java:1060)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1022)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1009)
	at org.h2.server.web.WebThread.process(WebThread.java:165)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.lang.Thread.run(Thread.java:748)
2019-03-16 10:08:24 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Column "NAME" not found; SQL statement:
select t0.id, t0.dept_name from department t0 order by name [42122-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:150)
	at org.h2.command.dml.Select.prepare(Select.java:858)
	at org.h2.command.Parser.prepareCommand(Parser.java:283)
	at org.h2.engine.Session.prepareLocal(Session.java:611)
	at org.h2.engine.Session.prepareCommand(Session.java:549)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1247)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:76)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:304)
	at com.zaxxer.hikari.pool.ProxyConnection.prepareStatement(ProxyConnection.java:318)
	at com.zaxxer.hikari.pool.HikariProxyConnection.prepareStatement(HikariProxyConnection.java)
	at io.ebeaninternal.server.query.CQuery.prepareBindExecuteQueryWithOption(CQuery.java:343)
	at io.ebeaninternal.server.query.CQuery.prepareBindExecuteQuery(CQuery.java:310)
	at io.ebeaninternal.server.query.CQueryEngine.findMany(CQueryEngine.java:349)
	at io.ebeaninternal.server.query.DefaultOrmQueryEngine.findMany(DefaultOrmQueryEngine.java:126)
	at io.ebeaninternal.server.core.OrmQueryRequest.findList(OrmQueryRequest.java:371)
	at io.ebeaninternal.server.core.DefaultServer.findList(DefaultServer.java:1506)
	at io.ebeaninternal.server.querydefn.DefaultOrmQuery.findList(DefaultOrmQuery.java:1239)
	at models.Department.findAll(Department.java:65)
	at controllers.EmployeeCRUDController.usersEmployee(EmployeeCRUDController.java:86)
	at router.Routes$$anonfun$routes$1.$anonfun$applyOrElse$14(Routes.scala:297)
	at play.core.routing.HandlerInvokerFactory$$anon$3.resultCall(HandlerInvoker.scala:134)
	at play.core.routing.HandlerInvokerFactory$$anon$3.resultCall(HandlerInvoker.scala:133)
	at play.core.routing.HandlerInvokerFactory$JavaActionInvokerFactory$$anon$8$$anon$2$$anon$1.invocation(HandlerInvoker.scala:108)
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:88)
	at play.http.DefaultActionCreator$1.call(DefaultActionCreator.java:31)
	at play.core.j.JavaAction.$anonfun$apply$8(JavaAction.scala:138)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:658)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:56)
	at play.api.libs.streams.Execution$trampoline$.execute(Execution.scala:70)
	at play.core.j.HttpExecutionContext.execute(HttpExecutionContext.scala:48)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:72)
	at scala.concurrent.impl.Promise$KeptPromise$Kept.onComplete(Promise.scala:372)
	at scala.concurrent.impl.Promise$KeptPromise$Kept.onComplete$(Promise.scala:371)
	at scala.concurrent.impl.Promise$KeptPromise$Successful.onComplete(Promise.scala:379)
	at scala.concurrent.impl.Promise.transform(Promise.scala:33)
	at scala.concurrent.impl.Promise.transform$(Promise.scala:31)
	at scala.concurrent.impl.Promise$KeptPromise$Successful.transform(Promise.scala:379)
	at scala.concurrent.Future.map(Future.scala:292)
	at scala.concurrent.Future.map$(Future.scala:292)
	at scala.concurrent.impl.Promise$KeptPromise$Successful.map(Promise.scala:379)
	at scala.concurrent.Future$.apply(Future.scala:658)
	at play.core.j.JavaAction.apply(JavaAction.scala:138)
	at play.api.mvc.Action.$anonfun$apply$2(Action.scala:96)
	at play.api.libs.streams.StrictAccumulator.$anonfun$mapFuture$4(Accumulator.scala:174)
	at scala.util.Try$.apply(Try.scala:213)
	at play.api.libs.streams.StrictAccumulator.$anonfun$mapFuture$3(Accumulator.scala:174)
	at scala.Function1.$anonfun$andThen$1(Function1.scala:57)
	at scala.Function1.$anonfun$andThen$1(Function1.scala:57)
	at play.api.libs.streams.StrictAccumulator$$anon$1.apply(Accumulator.scala:218)
	at play.api.libs.streams.StrictAccumulator$$anon$1.apply(Accumulator.scala:217)
	at java.util.function.Function.lambda$andThen$1(Function.java:88)
	at java.util.function.Function.lambda$andThen$1(Function.java:88)
	at play.libs.streams.Accumulator$StrictAccumulator$1.apply(Accumulator.java:403)
	at play.libs.streams.Accumulator$StrictAccumulator$1.apply(Accumulator.java:400)
	at scala.Function1.$anonfun$andThen$1(Function1.scala:57)
	at scala.Function1.$anonfun$andThen$1(Function1.scala:57)
	at play.api.libs.streams.StrictAccumulator.run(Accumulator.scala:207)
	at play.core.server.AkkaHttpServer.$anonfun$runAction$4(AkkaHttpServer.scala:376)
	at akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:41)
	at akka.http.scaladsl.util.FastFuture$.$anonfun$transformWith$3(FastFuture.scala:51)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:44)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
2019-03-16 21:16:16 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Table "EMPLOYEE" not found; SQL statement:
insert into employee (email, id, role, name, job_Title, work_Phone, salary, password,aid,department_id)
            values ('JohnSmith@jmc.com',1,'employee','John Smith','Secretary','08512345678',25000.00, 'password',9,1) [42102-197]
2019-03-16 21:16:16 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Table "EMPLOYEE" not found; SQL statement:
insert into employee (email, id, role, name, job_Title, work_Phone, salary, password,aid,department_id)
            values ('SeanWilliams@jmc.com',2,'employee','Sean Williams','Accountant','0855662616',27000.00, 'password',10,1) [42102-197]
2019-03-16 21:16:16 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Table "EMPLOYEE" not found; SQL statement:
insert into employee (email, id, role, name, job_Title, work_Phone, salary, password,aid,department_id)
            values ('BillMorris@jmc.com',3,'employee','Bill Morris','Auditor','08512345678',35000.00, 'password',11,1) [42102-197]
2019-03-16 21:16:16 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Table "EMPLOYEE" not found; SQL statement:
insert into employee (email, id, role, name, job_Title, work_Phone, salary, password,aid,department_id)
            values ('HenriettaFord@jmc.com',4,'manager','HenriettaFord','manager','08512345678',40000.00, 'password',12,1) [42102-197]
2019-03-17 23:23:11 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "EMPLOYEE" not found; SQL statement:
select t0.role, t0.email, t0.id, t0.role, t0.name, t0.job_title, t0.work_phone, t0.salary, t0.password, t0.AID, t0.department_id from employee t0 [42102-197]
2019-03-17 23:27:43 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "EMPLOYEE" not found; SQL statement:
select t0.role, t0.email, t0.id, t0.role, t0.name, t0.job_title, t0.work_phone, t0.salary, t0.password, t0.AID, t0.department_id from employee t0 [42102-197]
2019-03-17 23:51:40 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "DEPARTMENT" not found; SQL statement:
insert into department (dept_name) values ('Finance') [42102-197]
2019-03-17 23:51:40 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "DEPARTMENT" not found; SQL statement:
insert into department (dept_name) values ('Catering') [42102-197]
2019-03-17 23:51:40 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "DEPARTMENT" not found; SQL statement:
insert into department (dept_name) values ('Mining') [42102-197]
2019-03-17 23:51:40 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "DEPARTMENT" not found; SQL statement:
insert into department (dept_name) values ('Repairs') [42102-197]
2019-03-17 23:51:40 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "DEPARTMENT" not found; SQL statement:
insert into department (dept_name) values ('Logistics') [42102-197]
2019-03-17 23:51:40 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "DEPARTMENT" not found; SQL statement:
insert into department (dept_name) values ('Security') [42102-197]
2019-03-18 09:25:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "INSERT INTO EMPLOYEE (EMAIL, ID, ROLE, NAME, JOB_TITLE, WORK_PHONE, SALARY, PASSWORD,,[*]DEPARTMENT_ID)
            VALUES ('ChrisBarrie@jmc.com',1,'employee','Chris Barrie','Technician','08556654566',14000.00, 'password',4) "; expected "identifier"; SQL statement:
insert into employee (email, id, role, name, job_Title, work_Phone, salary, password,,department_id)
            values ('ChrisBarrie@jmc.com',1,'employee','Chris Barrie','Technician','08556654566',14000.00, 'password',4) [42001-197]
2019-03-18 09:25:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "INSERT INTO EMPLOYEE(AID)
            VALUES('1')
            WHERE[*] EMAIL = 'JohnSmith@jmc.com' "; SQL statement:
insert into employee(aid)
            values('1')
            where email = 'JohnSmith@jmc.com' [42000-197]
2019-03-18 09:27:21 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "DEPARTMENT" not found; SQL statement:
insert into department (dept_name) values ('Finance') [42102-197]
2019-03-18 09:27:21 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "DEPARTMENT" not found; SQL statement:
insert into department (dept_name) values ('Catering') [42102-197]
2019-03-18 09:27:21 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "DEPARTMENT" not found; SQL statement:
insert into department (dept_name) values ('Mining') [42102-197]
2019-03-18 09:27:21 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "DEPARTMENT" not found; SQL statement:
insert into department (dept_name) values ('Repairs') [42102-197]
2019-03-18 09:27:21 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "DEPARTMENT" not found; SQL statement:
insert into department (dept_name) values ('Logistics') [42102-197]
2019-03-18 09:27:21 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "DEPARTMENT" not found; SQL statement:
insert into department (dept_name) values ('Security') [42102-197]
2019-03-18 09:27:21 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "EMPLOYEE" not found; SQL statement:
insert into employee (email, id, role, name, job_Title, work_Phone, salary, password,department_id)
            values ('JohnSmith@jmc.com',1,'employee','John Smith','Secretary','08512345678',25000.00, 'password',1) [42102-197]
2019-03-18 09:27:21 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "EMPLOYEE" not found; SQL statement:
insert into employee (email, id, role, name, job_Title, work_Phone, salary, password,department_id)
            values ('SeanWilliams@jmc.com',2,'employee','Sean Williams','Accountant','0855662616',27000.00, 'password',1) [42102-197]
2019-03-18 09:27:21 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "EMPLOYEE" not found; SQL statement:
insert into employee (email, id, role, name, job_Title, work_Phone, salary, password,department_id)
            values ('BillMorris@jmc.com',3,'employee','Bill Morris','Auditor','085573755474',35000.00, 'password',1) [42102-197]
2019-03-18 09:27:21 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "EMPLOYEE" not found; SQL statement:
insert into employee (email, id, role, name, job_Title, work_Phone, salary, password,department_id)
            values ('HenriettaFord@jmc.com',4,'manager','HenriettaFord','manager','0855843975',40000.00, 'password',1) [42102-197]
2019-03-18 09:27:21 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "EMPLOYEE" not found; SQL statement:
insert into employee (email, id, role, name, job_Title, work_Phone, salary, password,,department_id)
            values ('ChrisBarrie@jmc.com',1,'employee','Chris Barrie','Technician','08556654566',14000.00, 'password',4) [42102-197]
2019-03-18 09:27:21 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "EMPLOYEE" not found; SQL statement:
insert into employee (email, id, role, name, job_Title, work_Phone, salary, password,department_id)
            values ('CraigCharles@jmc.com',2,'employee','Craig Charles','Technician','0857456556',14500.00, 'password',4) [42102-197]
2019-03-18 09:27:21 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "EMPLOYEE" not found; SQL statement:
insert into employee (email, id, role, name, job_Title, work_Phone, salary, password,department_id)
            values ('Robert Llewyn@jmc.com',3,'employee','Robert Llewyn','Cleaner','08598824447',19000.00, 'password',2) [42102-197]
2019-03-18 09:27:21 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "EMPLOYEE" not found; SQL statement:
insert into employee (email, id, role, name, job_Title, work_Phone, salary, password,department_id)
            values ('DannyJohn-Jules@jmc.com',4,'manager','Danny John-Jules','manager','0854646564',42000.00, 'password',3) [42102-197]
2019-03-18 09:27:21 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "EMPLOYEE" not found; SQL statement:
insert into employee (email, id, role, name, job_Title, work_Phone, salary, password,department_id)
            values ('ClareGrogan@jmc.com',1,'employee','Clare Grogan','Secretary','0856545567',25000.00, 'password',5) [42102-197]
2019-03-18 09:27:21 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "EMPLOYEE" not found; SQL statement:
insert into employee (email, id, role, name, job_Title, work_Phone, salary, password,department_id)
            values ('ChloeArnett@jmc.com',2,'employee','Chloe Arnett','Clerk','0857454464',27000.00, 'password',5) [42102-197]
2019-03-18 09:27:21 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "EMPLOYEE" not found; SQL statement:
insert into employee (email, id, role, name, job_Title, work_Phone, salary, password,department_id)
            values ('NormanLovett@jmc.com',3,'employee','Bill Morris','Clerk','08599547934',35000.00, 'password',5) [42102-197]
2019-03-18 09:27:21 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "EMPLOYEE" not found; SQL statement:
insert into employee (email, id, role, name, job_Title, work_Phone, salary, password,department_id)
            values ('HattieHayridge@jmc.com',4,'manager','Hattie Hayridge','manager','0854574398',40000.00, 'password',4) [42102-197]
2019-03-18 09:27:21 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "ADDRESS" not found; SQL statement:
insert into address (address1, address2, town_city, eircode, employee_email)  
            values  ('123 The Crescent','Beechbrook Gardens','Newbridge', 'S12 D354','JohnSmith@jmc.com') [42102-197]
2019-03-18 09:27:21 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "ADDRESS" not found; SQL statement:
insert into address (address1, address2, town_city, eircode, employee_email)  
            values  ('7565 The View','Babel Gardens','Navan', 'R32 D311','SeanWilliams@jmc.com') [42102-197]
2019-03-18 09:27:21 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "ADDRESS" not found; SQL statement:
insert into address (address1, address2, town_city, eircode, employee_email)  
            values  ('4 larch Rise','The Demesne','Kilcullen', 'S14 X180','BillMorris@jmc.com') [42102-197]
2019-03-18 09:27:21 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "ADDRESS" not found; SQL statement:
insert into address (address1, address2, town_city, eircode, employee_email)  
            values  ('The Manor','Kilbride','Port Laoise', 'DC2 S40','HenriettaFord@jmc.com') [42102-197]
2019-03-18 09:27:21 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "ADDRESS" not found; SQL statement:
insert into address (address1, address2, town_city, eircode, employee_email)  
            values  ('935 Ballysax','The Curragh','Newbridge', 'R32 RB26','ChrisBarrie@jmc.com') [42102-197]
2019-03-18 09:27:21 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "ADDRESS" not found; SQL statement:
insert into address (address1, address2, town_city, eircode, employee_email)  
            values  ('11 The Precint','Gardener Square','Donaghmede', 'S33 P321','CraigCharles@jmc.com') [42102-197]
2019-03-18 09:27:21 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "ADDRESS" not found; SQL statement:
insert into address (address1, address2, town_city, eircode, employee_email)  
            values  ('4 Oak Rise','Demesne View','Rostrevor', 'S11 F120','Robert Llewyn@jmc.com') [42102-197]
2019-03-18 09:27:21 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "ADDRESS" not found; SQL statement:
insert into address (address1, address2, town_city, eircode, employee_email)  
            values  ('Holyfield','Bloomfield','Tullamore', 'A90 2JZ','DannyJohn-Jules@jmc.com') [42102-197]
2019-03-18 09:27:21 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "ADDRESS" not found; SQL statement:
insert into address (address1, address2, town_city, eircode, employee_email)  
            values  ('123 The Crescent','Beechbrook Gardens','Newbridge', 'S12 D354','ClareGrogan@jmc.com') [42102-197]
2019-03-18 09:27:21 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "ADDRESS" not found; SQL statement:
insert into address (address1, address2, town_city, eircode, employee_email)  
            values  ('7565 The View','Babel Gardens','Navan', 'R32 D311','ChloeArnett@jmc.com') [42102-197]
2019-03-18 09:27:21 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "ADDRESS" not found; SQL statement:
insert into address (address1, address2, town_city, eircode, employee_email)  
            values  ('4 larch Rise','The Demesne','Kilcullen', 'S14 X180','NormanLovett@jmc.com') [42102-197]
2019-03-18 09:27:21 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "ADDRESS" not found; SQL statement:
insert into address (address1, address2, town_city, eircode, employee_email)  
            values  ('The Manor','Kilbride','Port Laoise', 'DC2 S40','HattieHayridge@jmc.com') [42102-197]
2019-03-18 09:27:21 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "EMPLOYEE" not found; SQL statement:
insert into employee(aid)
            values('1')
            where email = 'JohnSmith@jmc.com' [42102-197]
2019-03-18 09:27:21 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "PROJECT" not found; SQL statement:
insert into project (project_name, start_date, finish_date, allocated_budget)
            values  ('Testing', TO_DATE('17/12/2015', 'DD/MM/YYYY'), TO_DATE('23/03/2019', 'DD/MM/YYYY'), 1000000.00) [42102-197]
2019-03-18 09:28:07 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "INSERT INTO EMPLOYEE (EMAIL, ID, ROLE, NAME, JOB_TITLE, WORK_PHONE, SALARY, PASSWORD,,[*]DEPARTMENT_ID)
            VALUES ('ChrisBarrie@jmc.com',1,'employee','Chris Barrie','Technician','08556654566',14000.00, 'password',4) "; expected "identifier"; SQL statement:
insert into employee (email, id, role, name, job_Title, work_Phone, salary, password,,department_id)
            values ('ChrisBarrie@jmc.com',1,'employee','Chris Barrie','Technician','08556654566',14000.00, 'password',4) [42001-197]
2019-03-18 09:28:07 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "INSERT INTO EMPLOYEE(AID)
            VALUES('1')
            WHERE[*] EMAIL = 'JohnSmith@jmc.com' "; SQL statement:
insert into employee(aid)
            values('1')
            where email = 'JohnSmith@jmc.com' [42000-197]
2019-03-18 09:29:57 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "INSERT INTO EMPLOYEE(AID)
            VALUES('1')
            WHERE[*] EMAIL = 'JohnSmith@jmc.com' "; SQL statement:
insert into employee(aid)
            values('1')
            where email = 'JohnSmith@jmc.com' [42000-197]
2019-03-18 09:33:17 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "INSERT INTO EMPLOYEE(AID)
            VALUE[*]('1')
            WHERE EMAIL = 'JohnSmith@jmc.com' "; expected "DIRECT, SORTED, DEFAULT, VALUES, SET, (, WITH, SELECT, FROM"; SQL statement:
insert into employee(aid)
            value('1')
            where email = 'JohnSmith@jmc.com' [42001-197]
2019-03-18 09:33:30 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "INSERT INTO EMPLOYEE(AID)
            VALUES('1')
            WHERE[*] EMAIL = 'JohnSmith@jmc.com' "; SQL statement:
insert into employee(aid)
            values('1')
            where email = 'JohnSmith@jmc.com' [42000-197]
2019-03-18 09:33:43 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "INSERT INTO EMPLOYEE(AID)
            VALUES('1')
            WHERE[*] EMAIL= 'JohnSmith@jmc.com' "; SQL statement:
insert into employee(aid)
            values('1')
            where email= 'JohnSmith@jmc.com' [42000-197]
